<a href="https://colab.research.google.com/github/Cardomomo/PREPROCESSING/blob/main/1_CAROLINATORRESARJONA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CAROLINA TORRES ARJONA. DATA 3A
# UNIDAD 1 - DATA PREPROCESSING



#ESTE ES MI PRIMER EJEMPLO DE PYTHON - CAROLINA TORRES ARJONA.
#DATA 3A.

> Bloc con sangría???  TESTING
TESTING TESTING




    como si fuera codigo
    qué mas a ver
* Lista
* Elemento de la lista

## FUNCIONA COMO MARKDOWN



## BASICO 

In [ ]:
PI=3.1416
SALUDO="¡DEBERIA DECIR: SALUDOS!"
print(SALUDO)
print(PI)

¡DEBERIA DECIR: SALUDOS!
3.1416


In [ ]:
NOMBRE=input("INSERTA TU NOMBRE")


INSERTA TU NOMBREcarito


In [ ]:
print(NOMBRE,type(NOMBRE))

carito <class 'str'>


In [ ]:
A,B,C=13,"holaa",True
print(A)
print(B)
print(C)

13
holaa
True


In [ ]:
varent=3
otravarent=3638734
varentnegt=-133

In [ ]:
print(varent)
print(otravarent)
print(varentnegt)

3
3638734
-133


In [ ]:
varflot=37.3980
otravarflot=-328497.0867

In [ ]:
varent=True
varfalsa=False

In [ ]:
print(varent)
print(varfalsa)

True
False


In [ ]:
import sys
print(sys.getsizeof(1.0))
print(sys.getsizeof(""))
print(sys.getsizeof("Hello!"))
print(sys.getsizeof(dict()))
print(sys.getsizeof(dict({'a':1,'b':2})))
#TAMAÑO DE OBJETO EN BYTES

24
53
55
248
248


In [ ]:
nombre="CAROLINA"
edad=21

In [ ]:
print("ME LLAMO:",nombre)
print("TENGO",edad,"AÑOS")

ME LLAMO: CAROLINA
TENGO 21 AÑOS


In [ ]:
entero=3.3

type(entero)

float

In [ ]:
float(entero)
type(entero)

float

In [ ]:
DATO1=float(input())#CONVERTIR EN INT O FLOAT 
DATO2=int(input())#EL INPUT POR SI SOLO GUARDA EN STRING ASI QUE SE DEBE ESPECIFICAR
print(DATO1)
print(DATO2)
print(type(DATO1))
type(DATO2)

3
2
3.0
2
<class 'float'>


int

In [ ]:
SUMADATOS=DATO1+DATO2
print(SUMADATOS)
type(SUMADATOS)


5.0


float

In [ ]:
if (3>0):
  print("3 ES MAYOR QUE 0")#RECUERDA IDENTAR CORRECTAMENTE

3 ES MAYOR QUE 0


In [ ]:
if (3>0):
  print("3 ES MAYOR QU 0")
elif (3<5):
  print("3 ES MAYORQUE 2 TAMBIEN")
else:
  print("NEL")
  #SI EL IF ES TRUE ENTONCES NO AVANZA AL ELIF. 

3 ES MAYOR QU 0


In [ ]:

for n in range(10):
  print(n)


0
1
2
3
4
5
6
7
8
9


In [ ]:
lista=[3,13,"HEHE"]
for n in lista:
  print(n)#LISTA COMO ES PRESENTADA

3
13
HEHE


In [ ]:
listas=[6,13,33,"hola"]
for r in listas:
  print(r)
  

6
13
33
hola


In [ ]:
print(listas[2])#UN LUGAR DE UNA LISTA POSICION

33


In [ ]:
for n in range(-10,10,2):
  print(n)#DE 2 EN 2, DESDE -10 HASTA 10

-10
-8
-6
-4
-2
0
2
4
6
8


In [ ]:
i=1
while i<=6:
  print(i)
  i+=1
  #WHILE

1
2
3
4
5
6


In [ ]:
i=7
while True:
  print(i)
  i=i+1
  if(i>6):
    break
    #DO WHILE: CONDICION SE EVALUA AL FINAL, SE HACE AL MENOS UNA VEZ INCLUSO SI AL PRINCIPIO ES FALSE

7


In [ ]:
#INICIAMOS FUNCIONES---------------------------------------------------
def saludo():
  return "HOLA CARITO"
print(saludo())

HOLA CARITO


In [ ]:
def saludo2():
  print("HOLA DE NUEVO CARITO")
saludo2()

HOLA DE NUEVO CARITO


In [ ]:
def suma(a1,b1):
  return a1+b1


In [ ]:
def resta(a1,b1):
  return a1-b1

In [ ]:
x,y=5,4
ss=suma(x,y)
rr=resta(x,y)
print(ss)
print(rr)

9
1


In [ ]:
def caller(a1,b1):
  return suma(a1,b1), resta(b1,a1)#REGRESO 2 LLAMDAS A FUNCIONES PREVIAS


In [ ]:
x,y=10,13
llamada=caller(x,y)#LLAMO A LA F CALLER QUE LLAMARA A SU VEZ A FS suma Y resta.
print(llamada)

(23, 3)


In [ ]:
print(caller(3,3))

(6, 0)


In [ ]:
def numero(a):
  if a == 0:
    return "cero"
  elif a < 0:
    return "negativo"
  return "positivo"


print(numero(3))
print(numero(-1))
print(numero(0))

positivo
negativo
cero


##LIBRERIAS
* math
* panda
* numpy
* random

    SE IMPORTA COMO 
    import.LIBRERIA

In [ ]:
import numpy as np

## LISTA

In [ ]:
np.arange(10)#GENERO ARREGLO DE X VALORES

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
lista1 = np.linspace(0,10,3)#LISTA DE (x,y,z) DONDE x ES DESDE DONDE
#y ES HASTA DONDE
#z ES CON CUANTOS ELEMENTOS DENTRO DE LA LISTA
lista1

array([ 0.,  5., 10.])

In [ ]:
lista1.max()

10.0

In [ ]:
lista1.min()

0.0

In [ ]:
lista1.mean()

5.0

In [ ]:
lista1.std()

4.08248290463863

In [ ]:
type(lista1)

numpy.ndarray

In [ ]:
lista1.sum()

15.0

In [ ]:
np.median(lista1)

5.0

## ARRAY

In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B=np.mat(A)

In [ ]:
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
A*A#MULTIPLICA DIRECTAMENTE NO COMO MATRIZ

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
B*B#MULTIPLICA DE MANERA CORRECTA COMO UNA MATRIZ

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [ ]:
B.T #TRANSPUESTA LA MATRIZ

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
B.diagonal()

matrix([[1, 5, 9]])

## LIBRERIA RANDOM

In [ ]:
import random
items=["HIDALGO", "YUCATAN", "JALISCO", "QUERETARO", "JERRYRILANDIA", "DURANGO"]

In [ ]:
for i in range(13):
  print("-------UN DADO",random.randrange(1,7))
  print(".       .OTRO DADO",random.randrange(0,4))
  print(random.random())

-------UN DADO 5
.       .OTRO DADO 1
0.318894264810055
-------UN DADO 4
.       .OTRO DADO 2
0.8635242364530895
-------UN DADO 6
.       .OTRO DADO 3
0.19440054931883533
-------UN DADO 5
.       .OTRO DADO 3
0.835152834436364
-------UN DADO 6
.       .OTRO DADO 3
0.08851367582329617
-------UN DADO 6
.       .OTRO DADO 1
0.37078866399759636
-------UN DADO 2
.       .OTRO DADO 0
0.6294775431397143
-------UN DADO 2
.       .OTRO DADO 2
0.6900220889714965
-------UN DADO 5
.       .OTRO DADO 1
0.9734227699787715
-------UN DADO 2
.       .OTRO DADO 3
0.665674094221874
-------UN DADO 3
.       .OTRO DADO 3
0.08735645970474681
-------UN DADO 6
.       .OTRO DADO 0
0.8510226703236481
-------UN DADO 2
.       .OTRO DADO 0
0.9232050068457617


In [ ]:
print(random.choices(items,k=2))#TOMA K ELEMENTOS Y PUEDEN SER REPETIDOS

['DURANGO', 'YUCATAN']


In [ ]:
print(random.sample(items,3))#TOMA ELEMENTO DE LISTA PERO NOOO REPETIDOS

['YUCATAN', 'JERRYRILANDIA', 'JALISCO']


## LIBRERIA PANDA

In [ ]:
#importar datos

import pandas as pd
iris_data = pd.read_csv('sample_data/iris-data.csv')
iris_data.head()

sepal_length_cm  sepal_width_cm  ...  petal_width_cm        class
0              5.1             3.5  ...             0.2  Iris-setosa
1              4.9             3.0  ...             0.2  Iris-setosa
2              4.7             3.2  ...             0.2  Iris-setosa
3              4.6             3.1  ...             0.2  Iris-setosa
4              5.0             3.6  ...             0.2  Iris-setosa

[5 rows x 5 columns]

In [ ]:
iris_data.describe()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
count       150.000000      150.000000       150.000000      145.000000
mean          5.644627        3.054667         3.758667        1.236552
std           1.312781        0.433123         1.764420        0.755058
min           0.055000        2.000000         1.000000        0.100000
25%           5.100000        2.800000         1.600000        0.400000
50%           5.700000        3.000000         4.350000        1.300000
75%           6.400000        3.300000         5.100000        1.800000
max           7.900000        4.400000         6.900000        2.500000

In [7]:
iris_data.head()

sepal_length_cm  sepal_width_cm  ...  petal_width_cm        class
0              5.1             3.5  ...             0.2  Iris-setosa
1              4.9             3.0  ...             0.2  Iris-setosa
2              4.7             3.2  ...             0.2  Iris-setosa
3              4.6             3.1  ...             0.2  Iris-setosa
4              5.0             3.6  ...             0.2  Iris-setosa

[5 rows x 5 columns]

In [9]:
colum=iris_data.columns.tolist()
colum

['sepal_length_cm',
 'sepal_width_cm',
 'petal_length_cm',
 'petal_width_cm',
 'class']

In [10]:
colum=colum[:4]+colum[-2:]+colum[4:5]
colum

['sepal_length_cm',
 'sepal_width_cm',
 'petal_length_cm',
 'petal_width_cm',
 'petal_width_cm',
 'class',
 'class']

In [12]:
iris_data[colum]

sepal_length_cm  sepal_width_cm  ...           class           class
0                5.1             3.5  ...     Iris-setosa     Iris-setosa
1                4.9             3.0  ...     Iris-setosa     Iris-setosa
2                4.7             3.2  ...     Iris-setosa     Iris-setosa
3                4.6             3.1  ...     Iris-setosa     Iris-setosa
4                5.0             3.6  ...     Iris-setosa     Iris-setosa
..               ...             ...  ...             ...             ...
145              6.7             3.0  ...  Iris-virginica  Iris-virginica
146              6.3             2.5  ...  Iris-virginica  Iris-virginica
147              6.5             3.0  ...  Iris-virginica  Iris-virginica
148              6.2             3.4  ...  Iris-virginica  Iris-virginica
149              5.9             3.0  ...  Iris-virginica  Iris-virginica

[150 rows x 7 columns]

In [13]:
colum[1]

'sepal_width_cm'

In [14]:
otro=iris_data
otro[colum[0]]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length_cm, Length: 150, dtype: float64